### ISSUE TITLE
Write file to Object Storage Service with specific Content-type

### ISSUE THREAD

**Issue by ReyJust** [oracle/ocifs#28]
Hello 👋🏼 ,

Could someone indicate me how to change the content-type of a newly create item in Object Storage?
```
 # 19.Open a file for writing/flushing into file in OCI objectstorage bucket
 with fs.open("oci://<my_bucket>@<my_namespace>/<my_prefix>/hello.txt", 'w', autocommit=True) as f:
        f.write("Writing data to buffer, before manually flushing and closing.") # data is flushed and file closed
        f.flush()
```
Just like in the python SDK:
```
put_object_response = object_storage_client.put_object(
                namespace_name=namespace,
                bucket_name=bucket_name,
                object_name=filename,
                content_type=content_type,
                put_object_body=file.read(),
            )
```

Thanks!

**Comment by darenr** [comment]
Hi Justin,

I believe that the kwargs are faithfully passed into the underlying create call, try passing it through that way, if it doesn't work, open an issue and we'll get it fixed. Since the content type is a property oif the object it would need to be in the `open` call. In the case you provide though, the MIME type will correctly be set to the right content type for a text file. 

 with fs.open("oci://<my_bucket>@<my_namespace>/<my_prefix>/hello.txt", 'w', autocommit=True, content_type=content_type) as f:
        f.write("Writing data to buffer, before manually flushing and closing.") # data is flushed and file closed
        f.flush()

**Comment by darenr** [comment]
Thanks Justin, let me get this fixed for you. You don't need to do anything further. When you open a file for writing the library (when you don't pass in a content-type) should use the standard MIME type mapping to set the content-type, so for the example you gave you shouldn't even need to set it, but both implicit and explicit should work. I'll create the internal bug report to get a fix.

**Comment by dipatidar** [comment]
Hi @ReyJust, the latest version [1.3.1](https://pypi.org/project/ocifs/) supports both implicit and explicit setting of content-type for open operation when writing files in Object Storage. Here is example code. 

`# Ocifs sets the best-guessed content-type for hello.txt i.e "text/plain"
 with fs.open("oci://<my_bucket>@<my_namespace>/<my_prefix>/hello.txt", 'w', autocommit=True) as f:
        f.write("Writing data to buffer, before manually flushing and closing.") # data is flushed and file closed
        f.flush()
# Ocifs uses the specified content-type passed in the open while writing to OCI objectstorage bucket
 with fs.open("oci://<my_bucket>@<my_namespace>/<my_prefix>/hello.txt", 'w',content_type='text/plain') as f:
        f.write("Writing data to buffer, before manually flushing and closing.") # data is flushed and file closed
        f.flush()`
